---
galaxy_info:
  author: John Freeman
  description: Role for installing and configuring oh-my-zsh.
  company: GantSign Ltd.
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - 35
    - name: opensuse
      versions:
        - 15.3
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
  galaxy_tags:
    - ohmyzsh
    - zsh
    - shell
    - development
dependencies: []
