---

- hosts: 'hydra'
  tasks:
    - name: Install docker-compose python package
      pip:
        name: docker-compose==1.29.2 

    - import_tasks: ./tasks/caddy.yml
    - import_tasks: ./tasks/plausible.yml
    - import_tasks: ./tasks/adguard.yml
    - import_tasks: ./tasks/linkding.yml
    - import_tasks: ./tasks/miniflux.yml
    - import_tasks: ./tasks/monitoring.yml
    - import_tasks: ./tasks/syncthing.yml
